### ISSUE TITLE
Empty card names 

### ISSUE THREAD

**Issue by Kakadu** [supertriodo/Arena-Tracker#78]
I can't see any card names in a deck view. Both for ranked and arena

![screenshot_20171227_225955](https://user-images.githubusercontent.com/438226/34391896-aa3403ea-eb59-11e7-8bb9-36efdd934e13.png)

Here is the log output, if needed: https://gist.github.com/Kakadu/8b0dc267fe1a6d5d916f94743da3a367

**Comment by supertriodo** [comment]
It seem it failed to download hearthstone cards json. Restart Arena Tracker and give it a couple of minutes before playing. It should solve it by itself.

**Comment by Kakadu** [comment]
Can I see any download progress? I'm pretty sure that issue is somewhere else btw... I waited a long enough. I tried to remove `rm ~/.local/share/Arena\ Tracker/Hearthstone\ Cards -fr`. It downloads something after starting a draft but the bug still present.

**Comment by supertriodo** [comment]
In the log file you linked search for "https://api.hearthstonejson.com/v1/latest/all/cards.json"

There you can see how its failing downloading it, and keep retrying.

**Comment by supertriodo** [comment]
If the file cards.json is present on AT dir/Extra try deleting it to force it to be downloaded.

It's just an idea because I think you won't find that file.

**Comment by supertriodo** [comment]
Let me know if you get it fixed, if not we can always manually download the file in your computer is an easy and dirty fix. I can't do much else as this is not a problem of Arena Tracker, is a problem in your internet conection.

**Comment by Kakadu** [comment]
I fixed it by connecting to the Internet from another place. 

Can AT report a message in GUI about this kind of stuff?

**Comment by supertriodo** [comment]
Ok, great it works now. It don't think it's a common problem, it should keep retrying when failing to download something.

**Comment by supertriodo** [comment]
By the way Kakadu, I'm reviewing the patrons with premium active. If you are the Kakadu in my patron I think you haven't asked for premium from your account. You should do it to benefit from the premium features.

Follow this steps. https://www.patreon.com/posts/how-to-unlock-15926642

If you already did it but didn't get any reply from me let me know, maybe your internet connection is also giving you problems with the premium request.

**Comment by Kakadu** [comment]
@supertriodo I have sent a request just now

**Comment by supertriodo** [comment]
Ok, received and activated. Thx for your support!

**Comment by Kakadu** [comment]
btw, if the file was successfully downloaded and I go back to the buggy network I can't see the text on cards again!

**Comment by supertriodo** [comment]
Have you already tried? It's failing? Send me your Arena Tracker log.

**Comment by Kakadu** [comment]
https://gist.github.com/Kakadu/11376c7cf78a2d168a590d1148b66e27

**Comment by supertriodo** [comment]
Try to manually download this file
https://api.hearthstonejson.com/v1/22611/all/cards.json
and save it as cards.json in AT dir/Extra
[cards.json.zip](https://github.com/supertriodo/Arena-Tracker/files/1595147/cards.json.zip)

Just in case you cant download it I attached it as a zip, unzip it and put it on At dir/Extra

**Comment by supertriodo** [comment]
If that doesn't work I think I have found the problem. You internet can reach the cards.json version so it knows that there's a new one but when it try to download it fails. The problem is AT remove the old cards.json version when it realize there's a new version before downloading the new one.

I'll send to your patreon mail a new development version (linux static) with the changes needed. You still will have to manually put the cards.json file in AT dir/Extra but it won't be removed anymore.

**Comment by Kakadu** [comment]
No need in email. I can compile from sources.

**Comment by supertriodo** [comment]
I'm in the middle of some coding and I don't want to upload the changes in a hurry before a proper review. I sent the mail. We can continue talking via email.
